### ISSUE TITLE
Update charts to use colour blind friendly palettes

### ISSUE THREAD

**Issue by mrjoh3** [djpr-data/djprshiny#22]
First step here is find in https://github.com/djpr-data/djprtheme/issues/23

once the palettes exist adjust plot server and other similar functions to use the new palettes

**Comment by annett-djpr** [comment]
can be closed once PR in djprtheme is approved https://github.com/djpr-data/djprtheme/pull/24

**Comment by annett-djpr** [comment]
PR passed. Issue can be closed.
